### ISSUE TITLE
Face app tracker not woking

### ISSUE THREAD

**Issue by briancrisbravo** [PingguSoft/aTelloPilot#10]
I tested face tracker.  It detects my face but the box stays green.  When i move to the left or right, tello do not follow face. 

I have Vivo phone v7 model.

**Comment by PingguSoft** [comment]
Please check the wiki.

https://github.com/PingguSoft/aTelloPilot/wiki/06.-Face-tracking

1. turn face tracking on
2. several faces can be detected like the above picture
3. *click a face to track*
4. rectangle for selected face is changed to red one
5. drone will follow the face but it stops tracking when the face is missing
6. After selected face is missing if only one face is detected after
then, drone will track it asap


2019년 2월 24일 (일) 오후 2:36, briancrisbravo <notifications@github.com>님이 작성:
